### ISSUE TITLE
Searchable / Filterable redirect list with pagination

### ISSUE THREAD

**Issue by Sebobo** [neos/redirecthandler-ui#10]
Should be done after #8 

The following filters should be applicable:

* By status code
* System generated / manual redirects

UX specific:

* By default automatic redirects could be filtered to clean up the UI

**Comment by sbruggmann** [comment]
Would be great to integrate filter for automatically and manually created redirects: https://github.com/neos/redirecthandler/issues/18

**Comment by Sebobo** [comment]
Another interesting thing could be filtering by creation date to find old ones

**Comment by drlimbo** [comment]
> Would be great to integrate filter for automatically and manually created redirects: [neos/redirecthandler#18](https://github.com/neos/redirecthandler/issues/18)

A way to hide "automatically created redirects" would be awesome!

**Comment by kitsunet** [comment]
by lastHit would be super helpful too (if hit counter is enabled)

**Comment by Sebobo** [comment]
All sorting and filters are now there except the last hit by date as the column already orders by number of hits. Not sure yet how to do that in a good UX way. @kitsunet should I create an additional issue so we implement that in the future?
