### ISSUE TITLE
Help text or domain list for host name field

### ISSUE THREAD

**Issue by lorenzulrich** [neos/redirecthandler-ui#18]
![image](https://user-images.githubusercontent.com/1816023/63417624-eb1bf480-c401-11e9-9f89-2a48ea60590f.png)

The host name field currently suggests entering a domain. As a non-technical user, I cannot assume that I can leave this field empty and the redirect would be valid for all domains.

I think it would be user-friendly to render a select box. By default, the value would be `*` and the label "All domain". The other items would be fed from all (active?) domains in the domain management.

If this somehow doesn't make sense, I suggest to place a help text.

**Comment by Sebobo** [comment]
I would rather add "(optional)" behind the label.

Offering a select box is not enough as more domains than the configured ones might map on the Neos installation.

**Comment by lorenzulrich** [comment]
A HTML `<datalist>` element could be a solution for this. It's the combination of a select and a text field. Configured domains could be in the list, while any domain can be entered.

**Comment by Sebobo** [comment]
I like that idea, but this might go in the follow up release 👍

**Comment by drlimbo** [comment]
I'd love the idea of selecting a domain from a List 👍
