### ISSUE TITLE
Integrate package with Weblate for localisation 

### ISSUE THREAD

**Issue by Sebobo** [neos/redirecthandler-ui#20]

**Comment by Sebobo** [comment]
@kdambekalns can you support me with this?

**Comment by kdambekalns** [comment]
Yes, sure. Let me finally tackle the "understand that again and documeent it" first, ok?

**Comment by Sebobo** [comment]
@kdambekalns ping ;)

**Comment by kdambekalns** [comment]
I am currently evaluating Weblate as a replacement for CrowdIn, it looks really promising and would make adding new packages to the translation process way easier. Stay tuned!

**Comment by kdambekalns** [comment]
Done: https://hosted.weblate.org/projects/neos/neos-redirecthandler-ui-modules-master/
