### ISSUE TITLE
Composer cannot install package (Neos 4.3)

### ISSUE THREAD

**Issue by burakkavak** [neos/redirecthandler-ui#22]
I can't install this package using the newest Neos (4.3). I followed the instuctions and got this composer error:

>  Problem 1
>    - neos/redirecthandler-ui 2.0.0 requires neos/redirecthandler ~3.0 || dev-master -> satisfiable >by neos/redirecthandler[3.0.0].
>    - neos/redirecthandler-ui 2.0.1 requires neos/redirecthandler ~3.0 || dev-master -> satisfiable >by neos/redirecthandler[3.0.0].
>    - neos/redirecthandler-ui 2.0.2 requires neos/redirecthandler ~3.0 || ~4.0 -> satisfiable by >neos/redirecthandler[3.0.0, 4.0.0].
>    - neos/redirecthandler 4.0.0 requires neos/flow ^6.0 -> satisfiable by neos/flow[6.0.x-dev] but >these conflict with your requirements or minimum-stability.
>    - neos/redirecthandler 3.0.0 requires neos/redirecthandler-storageimplementation ~3.0 -> no >matching package found.
>    - Installation request for neos/redirecthandler-ui ^2.0 -> satisfiable by neos/redirecthandler->ui[2.0.0, 2.0.1, 2.0.2].
>
>Potential causes:
> - A typo in the package name
> - The package is not available in a stable-enough version according to your minimum-stability >setting
>   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
> - It's a private package and you forgot to add a custom repository to find it
>
>Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

My composer.json:
[composer.zip](https://github.com/neos/redirecthandler-ui/files/3600105/composer.zip)

**Comment by Sebobo** [comment]
Hi, thanks for the report.

Did you already explicitly require `neos/redirecthandler-databasestorage`?

**Comment by burakkavak** [comment]
Yes, explicitly requiring `neos/redirecthandler-databasestorage` yields the same error message.

**Comment by burakkavak** [comment]
I updated from Neos 4.0 -> 4.3 recently and used the composer.json from `neos/neos-base-distribution` where these two dependencies are listed:

> "neos/redirecthandler-neosadapter": "~3.0",
> "neos/redirecthandler-databasestorage": "~3.0"

Using the versions you provided worked, thanks!
