### ISSUE TITLE
Import & export file with redirect entries

### ISSUE THREAD

**Issue by jonnitto** [neos/redirecthandler-ui#3]
It would be great if it would be possible to import and export a .csv list. Just like the `redirect:import` and `redirect:export` command from the CLI

**Comment by Sebobo** [comment]
And I assume import would be also helpful

**Comment by mficzel** [comment]
It would be good to add the csv-library as dependency (redirecthandler only suggests "league/csv") which always leads to expected functionality not working from the start. This could also be adjusted in the redirecthandler itself.

**Comment by Sebobo** [comment]
So we should first refactor `redirecthandler` and then make those functions available in the UI here.
