### ISSUE TITLE
Allow redirects from "illegal" chars

### ISSUE THREAD

**Issue by kdambekalns** [neos/redirecthandler-ui#40]
When trying to create a redirect from `interview/kinder_fotografieren` to `interview/kinder-fotografieren` the UI disallows submitting the form. This is because the source path is checked against the pattern `^[a-zA-Z0-9\-\/\.]+$`, mimicking the allowed paths in Neos.

In my case that is precisely whe the redirect is needed, Wordpress allowed `_`, Neos does not. I hacked the pattern (using the web inspector), and could store and use the redirect just fine.

What other characters could/should be allowed here?

**Comment by kdambekalns** [comment]
Haha, should be solved with https://github.com/neos/redirecthandler-ui/pull/32 already.

**Comment by Sebobo** [comment]
As I was sure that the regex might always have some missing part you can modify in the settings. But you have to do it for both packages, redirect handler and the ui.

Initially I focused on the regex that we use for node uris that's why some specials were missing.
