### ISSUE TITLE
Export to CSV does not offer download

### ISSUE THREAD

**Issue by kdambekalns** [neos/redirecthandler-ui#48]
With the latest version on a current Neos 5 the export does not work. Clicking export brings me back to the list, the request sent does not even mention the `exportCsv` action, even though the form's action attribute does.

Probably because some JS submit magic goes wrong, the console shows `Empty string passed to getElementById().` when I click the export button.

**Comment by Sebobo** [comment]
Can confirm, but I don't get the js error and there is also no custom js for this view.

Not sure currently why this doesn't work anymore. Opening the form url directly will yield the correct result and the csv is downloaded.
