### ISSUE TITLE
Redirects to another domain with same path is not possible

### ISSUE THREAD

**Issue by jonnitto** [neos/redirecthandler-ui#51]
It is not possible to create a redirect to another URL with the same path: 
Example:
`/urisegment` to `https://sub.domain.tld/urisegment`
In the CLI I can create this redirect without any problems

**Comment by Sebobo** [comment]
This was intended as it could create a recursive redirect.

**Comment by Sebobo** [comment]
But if you set a domain it should work fine right?

**Comment by Sebobo** [comment]
Closing it as no response came for a year
