### ISSUE TITLE
Change MAX_INPUT_LENGTH

### ISSUE THREAD

**Issue by gerdemann** [neos/redirecthandler-ui#58]
You can currently only add URLs up to 255 characters via the UI.
Can this be increased? According to the domain model, up to 500 characters can be added to the target:
https://github.com/neos/redirecthandler-databasestorage/blob/1.0/Classes/Domain/Model/Redirect.php#L73

**Comment by Sebobo** [comment]
Sure, should be enough to change https://github.com/neos/redirecthandler-ui/blob/fd6245ac74eadb975f70195afab531361b5d9cd4/Resources/Private/JavaScript/components/RedirectForm.tsx#L10

**Comment by gerdemann** [comment]
The sourceUriPath can be up to 4000 characters long, should I set this to 4000?
https://github.com/neos/redirecthandler-databasestorage/blob/1.0/Classes/Domain/Model/Redirect.php#L56

If this is just this little adjustment, I would create a pull request.

**Comment by Sebobo** [comment]
Maybe start with both 500. I'm not sure if it creates more problems with 4000 ;)

From what I read urls should stay shorter than 2000 characters.
