### ISSUE TITLE
Improve UX for adding and editing redirects

### ISSUE THREAD

**Issue by Sebobo** [neos/redirecthandler-ui#6]
## Current behavior 

After I add or update a redirect only that redirect is shown without an explanation.

First I thought this was a bug and only after looking at the code I saw that it "searches" for it after updating it.

It's also a bit hard to guess how to use the search feature.

## Idea

* Split the controller code to actually use `actions` instead of the conditions based on the arguments.
* Separate search from `add`-feature and maybe just use one field which allows searching in all redirect fields.
* Give note to user when search happened and for what and how to reset it.
* Have a dropdown for `Status Code` with explanations instead of the free input

**Comment by Sebobo** [comment]
I propose the following (which we shortly discussed during the Dresden sprint):

For creating a new redirect we do something like a little wizard.

Option 1 is they want to create a non-redirect status (like 404):

1. User selects a non-redirect status type(from a dropdown).
2. We only show the source url and the confirmation button says "Set status".
3. We check if the source url is a page and go back to step 2 with a warning.
4. We store the new redirect and show a success message and the updated list.

Option 2 is they want to create a redirect (like 301):

1. User selects a redirect status type (from a dropdown)
2. We show the source and target url fields.
3. We do checks whether the source url is an existing page and go back to step 2 and show a warning if that's the case (as the redirect wouldn't work).
4. We check whether an existing redirect with the same source url exists and go back to step 2 with a warning.
5. We check whether the target url actually exits and go back to step 2 with a warning if not.
6. We store the new redirect and show a success message and the updated list.

The idea is based on some discussion and diagrams I had with the friends from Yoast and how they do it in Wordpress.

**Comment by Sebobo** [comment]
@mficzel @sbruggmann you can chime in with your ideas :)

**Comment by sbruggmann** [comment]
Sounds reasonable and like the way to go.
Just one addition: One big UX improvement would be to hide automatically generated redirects in the default view (https://github.com/neos/redirecthandler-ui/issues/10#issuecomment-494334239)
