### ISSUE TITLE
redirect of non-primary domain does not work

### ISSUE THREAD

**Issue by kusiboss** [neos/redirecthandler-ui#76]
Hello,

A redirect from www.website.fr to www.website.ch/fr does not work.

Primary domain: www.website.ch
Other domain: www.website.fr

origin domain: www.website.fr
source path: [empty]
target uri or path: https://www.website.ch/fr
code: 301

Not sure if I am right here or if it is a problem of another package. Thanks for looking into.

**Comment by Sebobo** [comment]
Hi @kusiboss,

we currently do not support redirects of the base uri in this package family as those are better managed in the webserver config including forwarding the path and parameters.
