### ISSUE TITLE
Refactor fluid to Fusion templating

### ISSUE THREAD

**Issue by Sebobo** [neos/redirecthandler-ui#8]
This can be similarly done like in the history controller of Neos and would lead to the following benefits:

* Easier to modify and extend
* We don't use form helpers for now but later replace the used form html tags with fusion forms in Neos 5.0 (planned)
* We want to have Fusion based backend modules in the long term

**Comment by Sebobo** [comment]
@sbruggmann @mficzel should we do this together with #6 or do it non-breaking and just with small improvements?

**Comment by Sebobo** [comment]
Should we also think about showing the hit counter and creation date?

**Comment by mficzel** [comment]
(yes) If hit counting is enabled.

BTW: I consider enabling hitCounting by default a problem but this is in the redirecthandler package itself.

**Comment by Sebobo** [comment]
Yes me too, see #11
