### ISSUE TITLE
Rendering breaks when too many redirects exist

### ISSUE THREAD

**Issue by gradinarufelix** [neos/redirecthandler-ui#82]
We faced a strange error where the whole rendering broke and no HTML was rendered at all. We found out that if the JSON with the redirects is too big, the browser rendering breaks. I already found a fix where we would move the redirects JSON to a separate script tag and get the data from it, which works. I'll prepare a pull request tomorrow.

**Comment by Sebobo** [comment]
Thx for resolving this. Fix is in 2.4.5
